### PR TITLE
Add option to look for CM with specific USB path.

### PR DESCRIPTION
**Pull request by burtyb**
Adds "-p" option with works similar to the port number but accepts a USB pathname (like 1-1.3.1).

### CODE REVIEW

**Comment by nbuchwitz** [comment]
@pelwell /others Do you see any chance that this can get a review? I think filtering by usb paths can be quite useful

**Comment by timg236** [comment]
Can you give an example about how this would be used?

**Comment by nbuchwitz** [comment]
We have multiple automatic provisioning systems for CM/CM3/CM4S which consists out of 8 SO-DIMM sockets attached to 2 USB hubs. By specifying the port with a path, I can run different instances for the ports. The current approach with `-1` - `-9` doesn't work here as the devices are scattered over different hubs and ports

**Comment by timg236** [comment]
ok LGTM

**Comment by earcam** [comment]
@burtyb you've made my day, thank you  (wish I'd run `rpiboot --help` and spotted the `-p` option)

**Pull request merged**
