### PR TITLE
Added Docker build chain

### PR DESCRIPTION
**Pull request by GeorgeSapkin**
This simplifies building on any machine that has Docker without installing any build dependencies.

### CODE REVIEW

**Comment by mi-hol** [comment]
it seems this change was actually implemented (maybe without merging) hence could be closed

**Comment by timg236** [comment]
I don't think this is something that Raspberry Pi would use or maintain

**Comment by mi-hol** [comment]
> this change was actually implemented

Oops I was looking at the wrong file.
@timg236 , I can understand your reply but was original poster made aware?
Just leaving a PR unanswered & unactioned isn't a good practice :(

**Comment by pelwell** [comment]
PRs which aren't obviously wanted are often let to sit around for a while in case one of decides it is worth having after all, or perhaps the OP makes changes or just prods, but closing also works.

**Comment by mi-hol** [comment]
"house keeping" activities help to keep a "house" clean, from my view the same concepts (like "spring cleaning" ) help a repository to stay in order.

**Pull request closed without merging**
