### PR TITLE
Raspberry Pi 5: Add support for flashing the EEPROM and a 64-bit mass-storage-gadget for BCM2711 and BCM2712

### PR DESCRIPTION
**Pull request by timg236**

### CODE REVIEW

**Comment by timg236** [comment]
@peterharperuk @pelwell

**Comment by acmpo6ou** [comment]
Wow, that's a lot of work for RPi 5. Thank you!

**Comment by timg236** [comment]
> Wow, that's a lot of work for RPi 5. Thank you!

Removing start4.elf forced my hand slightly so I decided to fix the DDR init properly :)

**Comment by timg236** [comment]
Merging PR - the APT release will happen in the new year in-case of regressions

**Pull request merged**
